# Generated by Django 3.0.8 on 2021-05-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0002_auto_20210519_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.Dish')),
                ('ingredientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.Ingredient')),
            ],
        ),
    ]
