# Generated by Django 3.0.8 on 2021-05-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0004_auto_20210519_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish_ingredient',
            old_name='dish_Id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='dish_ingredient',
            old_name='ingredient_Id',
            new_name='ingredient',
        ),
    ]
