# Generated by Django 3.0.8 on 2021-05-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0006_meal_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal_Options_Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.Dish')),
                ('meal_option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.Meal_Option')),
            ],
        ),
    ]
