# Generated by Django 3.0.8 on 2021-05-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0007_meal_options_dishes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal_options_dishes',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='meal_options_dishes',
            old_name='meal_option_id',
            new_name='meal_option',
        ),
    ]
