# Generated by Django 3.0.8 on 2021-05-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0008_auto_20210519_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Meal_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.Meal_Option')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.Menu')),
            ],
        ),
    ]
