# Generated by Django 3.0.8 on 2021-05-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0009_menu_menu_meal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
