# Generated by Django 3.0.8 on 2021-05-21 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0010_menu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.Menu')),
            ],
        ),
    ]
