# Generated by Django 3.0.8 on 2021-05-21 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0011_daily_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_menu',
            name='day_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_service.Menu'),
        ),
    ]
