# Generated by Django 3.0.8 on 2021-05-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0012_auto_20210521_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_menu',
            old_name='day_menu',
            new_name='menu',
        ),
    ]
