# Generated by Django 3.0.8 on 2021-05-22 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0015_ordered_dishes_ordered_dishes_ingredients_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
