# Generated by Django 3.0.8 on 2021-05-24 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0018_auto_20210523_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.UUIDField(default='b95ccdbf-a9a2-4e74-ab8c-481a2040ec6f', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordered_dishes_ingredients_details',
            name='ordered_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.Dish'),
        ),
    ]
