# Generated by Django 3.0.8 on 2021-05-24 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0019_auto_20210524_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_dishes_ingredients_details',
            name='ordered_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.Ordered_Dishes'),
        ),
    ]
