# Generated by Django 3.0.8 on 2021-05-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0022_auto_20210524_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish_ingredient',
            name='dish',
        ),
        migrations.AddField(
            model_name='dish_ingredient',
            name='dish_option',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='menu_service.Meal_Options_Dishes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal_options_dishes',
            name='meal_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.Menu_Meal_Options'),
        ),
    ]
