# Generated by Django 3.0.8 on 2021-05-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_service', '0023_auto_20210525_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish_ingredient',
            name='dish_option',
        ),
        migrations.AddField(
            model_name='dish_ingredient',
            name='dish',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='menu_service.Dish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal_options_dishes',
            name='meal_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_service.Meal_Option'),
        ),
    ]
